services:
  inpeta-db:
    image: postgis/postgis:15-3.3
    container_name: inpeta_postgres
    restart: always
    environment:
      POSTGRES_USER: admin_inpeta
      POSTGRES_PASSWORD: password_rahasia
      POSTGRES_DB: db_inpeta
    ports:
      - "5433:5432"
    volumes:
      - inpeta_data:/var/lib/postgresql/data

volumes:
  inpeta_data: